name: Cross-Platform Check

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
        elif [ "$RUNNER_OS" = "macOS" ]; then
          brew update
          brew install cmake
        fi
        
    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_C_STANDARD=11 -DBUILD_TESTING=ON
        cmake --build .
        ctest --output-on-failure
