name: Windows CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    # 1. Setup MSYS2 with UCRT64 toolchain
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      id: setup-msys2
      with:
        msystem: UCRT64
        update: true
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          cmake
          ninja
          ccache

    # 2. Configure environment
    - name: Setup build environment
      shell: pwsh
      run: |
        # Add MSYS2 to PATH
        $msysPath = "C:\msys64\ucrt64\bin;C:\msys64\usr\bin"
        $env:PATH = "$msysPath;$env:PATH"
        
        # Verify tools
        gcc --version
        g++ --version
        ninja --version
        cmake --version

    # 3. Build
    - name: Configure and Build
      shell: pwsh
      run: |
        mkdir -p build
        cd build
        cmake .. -G "Ninja" `
          -DCMAKE_C_COMPILER=gcc `
          -DCMAKE_CXX_COMPILER=g++ `
          -DCMAKE_MAKE_PROGRAM=ninja
        cmake --build .

    - name: Run Tests
      shell: pwsh
      run: |
        cd build
        ctest --output-on-failure
