name: Windows CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    # 1. Cache Setup
    - name: Cache MSYS2 and build
      uses: actions/cache@v3
      id: ci-cache
      with:
        path: |
          C:\msys64
          build
          C:\Users\runneradmin\.cache\ccache
        key: ${{ runner.os }}-msys2-${{ hashFiles('**/CMakeLists.txt') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-msys2-${{ hashFiles('**/CMakeLists.txt') }}
          ${{ runner.os }}-msys2-

    # 2. Primary MSYS2 Setup (with cache-aware update)
    - name: Setup MSYS2 (Primary Attempt)
      uses: msys2/setup-msys2@v2
      id: msys2-setup
      continue-on-error: true  # Allows fallback to proceed
      with:
        update: ${{ !steps.ci-cache.outputs.cache-hit }}  # Only update if no cache
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          cmake
          ninja
          ccache

    # 3. Fallback Setup (if primary fails)
    - name: Setup MSYS2 (Fallback)
      if: steps.msys2-setup.outcome == 'failure'
      uses: msys2/setup-msys2@v2
      with:
        update: true  # Force fresh update
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          cmake
          ninja
          ccache

    # 4. Build with CCache
    - name: Configure and Build
      shell: msys2 {0}
      env:
        CCACHE_DIR: C:\Users\runneradmin\.cache\ccache
      run: |
        mkdir -p build
        cd build
        cmake -G "Ninja" .. \
          -DBUILD_TESTING=ON \
          -DCMAKE_C_STANDARD=11 \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
        cmake --build . -- -j 2

    # 5. Tests
    - name: Run Tests
      shell: msys2 {0}
      run: |
        cd build
        ctest --output-on-failure --timeout 120  # Extended timeout

    # 6. Post-job cache cleanup (optional)
    - name: Trim CCache
      if: always()
      shell: msys2 {0}
      run: |
        ccache --show-stats
        ccache --trim-size=500M  # Keep cache under control
