name: Windows CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    # 1. Install Ninja properly (native Windows version)
    - name: Install Ninja
      shell: pwsh
      run: |
        choco install ninja -y
        $env:Path += ";C:\ProgramData\chocolatey\bin"

    # 2. Setup MSYS2 (unchanged)
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          cmake
          ccache

    # 3. Build using native Ninja + MSYS2 tools
    - name: Configure and Build
      shell: pwsh
      env:
        CC: 'C:\msys64\ucrt64\bin\gcc.exe'
        CXX: 'C:\msys64\ucrt64\bin\g++.exe'
      run: |
        mkdir build
        cd build
        cmake .. -G "Ninja" `
          -DCMAKE_C_COMPILER="$env:CC" `
          -DCMAKE_CXX_COMPILER="$env:CXX" `
          -DCMAKE_MAKE_PROGRAM=ninja
        ninja
        
    - name: Run Tests
      shell: msys2 {0}
      run: |
        cd build
        ctest --output-on-failure --timeout 120  # Extended timeout

    # 6. Post-job cache cleanup (optional)
    - name: Trim CCache
      if: always()
      shell: msys2 {0}
      run: |
        ccache --show-stats
        ccache --trim-size=500M  # Keep cache under control
