name: Windows CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    # 1. Setup MSYS2 only
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          cmake
          ccache

    # 2. Build using native Ninja + MSYS2 tools
    - name: Configure and Build
      shell: pwsh
      env:
        CC: 'C:\msys64\ucrt64\bin\gcc.exe'
        CXX: 'C:\msys64\ucrt64\bin\g++.exe'
      run: |
        # Verify tools
        & "C:\msys64\ucrt64\bin\gcc.exe" --version
        ninja --version
        
        mkdir build -Force
        cd build
        cmake .. -G "Ninja" `
          -DCMAKE_C_COMPILER="$env:CC" `
          -DCMAKE_CXX_COMPILER="$env:CXX"
        cmake --build .

    - name: Run Tests
      shell: pwsh
      run: |
        cd build
        ctest --output-on-failure
