name: Windows CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    # 1. Setup MSYS2 with UCRT64 toolchain
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          cmake
          ninja
          ccache

    # 2. Build using native Windows Ninja + MSYS2 tools
    - name: Configure and Build
      shell: pwsh
      env:
        PATH: 'C:\msys64\ucrt64\bin;C:\Program Files\CMake\bin;$env:PATH'
      run: |
        # Verify tools
        gcc --version
        ninja --version
        
        mkdir build -Force
        cd build
        cmake .. -G "Ninja" `
          -DCMAKE_C_COMPILER="C:/msys64/ucrt64/bin/gcc.exe" `
          -DCMAKE_CXX_COMPILER="C:/msys64/ucrt64/bin/g++.exe" `
          -DCMAKE_MAKE_PROGRAM="ninja"
        ninja

    - name: Run Tests
      shell: pwsh
      run: |
        cd build
        ctest --output-on-failure
