name: Windows CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    # 1. Setup MSYS2 with UCRT64 toolchain
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          cmake
          ninja
          ccache

    # 2. Build using MSYS2 shell context
    - name: Configure and Build
      shell: msys2 {0}  # Critical change - use msys2 shell
      env:
        CCACHE_DIR: /c/Users/runneradmin/.cache/ccache
      run: |
        # Verify tools
        gcc --version
        g++ --version
        ninja --version
        
        mkdir -p build
        cd build
        cmake .. -G "Ninja" \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_MAKE_PROGRAM=ninja
        ninja

    - name: Copy DLL for tests
      shell: msys2 {0}
      run: |
        cp bin/llist.dll tests/

    - name: Debug Test Environment
      shell: msys2 {0}
      run: |
        cd build
        ldd tests/test_llist  # Check shared libs on Linux
        ls -la bin/           # Verify DLL exists
        ./tests/test_llist    # Run directly for more output
    
    - name: Run Tests
      shell: msys2 {0}
      run: |
        cd build
         ctest --output-on-failure --verbose
