name: Windows CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSYS2 UCRT64
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/msys2/msys2-installer/releases/download/latest/msys2-x86_64.exe" -OutFile "msys2.exe"
        Start-Process -Wait -FilePath "./msys2.exe" -ArgumentList "--quiet --install --root C:/msys64"
        C:\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm"
        C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm --needed base-devel mingw-w64-ucrt-x86_64-toolchain cmake"
        
    - name: Configure and Build
      shell: pwsh
      run: |
        $env:Path = "C:\msys64\ucrt64\bin;C:\msys64\usr\bin;$env:Path"
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" .. -DBUILD_TESTING=ON -DCMAKE_C_STANDARD=11
        cmake --build .
        
    - name: Run Tests
      shell: pwsh
      run: |
        $env:Path = "C:\msys64\ucrt64\bin;C:\msys64\usr\bin;$env:Path"
        cd build
        ctest --output-on-failure
